import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export interface ReportData {
  title: string;
  date: string;
  cameras: number;
  alerts: number;
  incidents: number;
  type: 'Security' | 'Monthly' | 'Weekly' | 'Incident' | 'Custom';
  content: string;
  charts?: any[];
}

export class PDFReportGenerator {
  private doc: jsPDF;

  constructor() {
    this.doc = new jsPDF();
  }

  async generateSecurityReport(data: ReportData): Promise<Blob> {
    // Set up the document
    this.doc.setFontSize(20);
    this.doc.text('Aegis Spectra Security Report', 20, 30);
    
    this.doc.setFontSize(12);
    this.doc.text(`Generated: ${data.date}`, 20, 45);
    this.doc.text(`Report Type: ${data.type}`, 20, 55);

    // Add summary section
    this.doc.setFontSize(16);
    this.doc.text('Summary', 20, 75);
    
    this.doc.setFontSize(10);
    this.doc.text(`Total Cameras: ${data.cameras}`, 20, 90);
    this.doc.text(`Total Alerts: ${data.alerts}`, 20, 100);
    this.doc.text(`Total Incidents: ${data.incidents}`, 20, 110);

    // Add content
    this.doc.setFontSize(14);
    this.doc.text('Report Details', 20, 130);
    
    this.doc.setFontSize(10);
    const splitContent = this.doc.splitTextToSize(data.content, 170);
    this.doc.text(splitContent, 20, 145);

    // Add footer
    this.doc.setFontSize(8);
    this.doc.text('Generated by Aegis Spectra Security System', 20, 280);
    this.doc.text(`Page 1 of 1`, 170, 280);

    return this.doc.output('blob');
  }

  async generateMonthlyReport(data: ReportData): Promise<Blob> {
    // Set up the document
    this.doc.setFontSize(20);
    this.doc.text('Aegis Spectra Monthly Report', 20, 30);
    
    this.doc.setFontSize(12);
    this.doc.text(`Month: ${data.date}`, 20, 45);
    this.doc.text(`Report Type: ${data.type}`, 20, 55);

    // Add monthly statistics
    this.doc.setFontSize(16);
    this.doc.text('Monthly Statistics', 20, 75);
    
    this.doc.setFontSize(10);
    this.doc.text(`Active Cameras: ${data.cameras}`, 20, 90);
    this.doc.text(`Alerts Generated: ${data.alerts}`, 20, 100);
    this.doc.text(`Security Incidents: ${data.incidents}`, 20, 110);

    // Add monthly trends
    this.doc.setFontSize(14);
    this.doc.text('Monthly Trends', 20, 130);
    
    this.doc.setFontSize(10);
    const splitContent = this.doc.splitTextToSize(data.content, 170);
    this.doc.text(splitContent, 20, 145);

    // Add footer
    this.doc.setFontSize(8);
    this.doc.text('Generated by Aegis Spectra Security System', 20, 280);
    this.doc.text(`Page 1 of 1`, 170, 280);

    return this.doc.output('blob');
  }

  async generateWeeklyReport(data: ReportData): Promise<Blob> {
    // Set up the document
    this.doc.setFontSize(20);
    this.doc.text('Aegis Spectra Weekly Report', 20, 30);
    
    this.doc.setFontSize(12);
    this.doc.text(`Week: ${data.date}`, 20, 45);
    this.doc.text(`Report Type: ${data.type}`, 20, 55);

    // Add weekly statistics
    this.doc.setFontSize(16);
    this.doc.text('Weekly Statistics', 20, 75);
    
    this.doc.setFontSize(10);
    this.doc.text(`Active Cameras: ${data.cameras}`, 20, 90);
    this.doc.text(`Alerts Generated: ${data.alerts}`, 20, 100);
    this.doc.text(`Security Incidents: ${data.incidents}`, 20, 110);

    // Add weekly analysis
    this.doc.setFontSize(14);
    this.doc.text('Weekly Analysis', 20, 130);
    
    this.doc.setFontSize(10);
    const splitContent = this.doc.splitTextToSize(data.content, 170);
    this.doc.text(splitContent, 20, 145);

    // Add footer
    this.doc.setFontSize(8);
    this.doc.text('Generated by Aegis Spectra Security System', 20, 280);
    this.doc.text(`Page 1 of 1`, 170, 280);

    return this.doc.output('blob');
  }

  async generateIncidentReport(data: ReportData): Promise<Blob> {
    // Set up the document
    this.doc.setFontSize(20);
    this.doc.text('Aegis Spectra Incident Report', 20, 30);
    
    this.doc.setFontSize(12);
    this.doc.text(`Date: ${data.date}`, 20, 45);
    this.doc.text(`Report Type: ${data.type}`, 20, 55);

    // Add incident details
    this.doc.setFontSize(16);
    this.doc.text('Incident Details', 20, 75);
    
    this.doc.setFontSize(10);
    this.doc.text(`Cameras Involved: ${data.cameras}`, 20, 90);
    this.doc.text(`Alerts Triggered: ${data.alerts}`, 20, 100);
    this.doc.text(`Incidents: ${data.incidents}`, 20, 110);

    // Add incident description
    this.doc.setFontSize(14);
    this.doc.text('Incident Description', 20, 130);
    
    this.doc.setFontSize(10);
    const splitContent = this.doc.splitTextToSize(data.content, 170);
    this.doc.text(splitContent, 20, 145);

    // Add footer
    this.doc.setFontSize(8);
    this.doc.text('Generated by Aegis Spectra Security System', 20, 280);
    this.doc.text(`Page 1 of 1`, 170, 280);

    return this.doc.output('blob');
  }

  async generateCustomReport(data: ReportData): Promise<Blob> {
    // Set up the document
    this.doc.setFontSize(20);
    this.doc.text('Aegis Spectra Custom Report', 20, 30);
    
    this.doc.setFontSize(12);
    this.doc.text(`Generated: ${data.date}`, 20, 45);
    this.doc.text(`Report Type: ${data.type}`, 20, 55);

    // Add custom content
    this.doc.setFontSize(16);
    this.doc.text('Report Content', 20, 75);
    
    this.doc.setFontSize(10);
    const splitContent = this.doc.splitTextToSize(data.content, 170);
    this.doc.text(splitContent, 20, 90);

    // Add footer
    this.doc.setFontSize(8);
    this.doc.text('Generated by Aegis Spectra Security System', 20, 280);
    this.doc.text(`Page 1 of 1`, 170, 280);

    return this.doc.output('blob');
  }

  async generateReport(data: ReportData): Promise<Blob> {
    switch (data.type) {
      case 'Security':
        return this.generateSecurityReport(data);
      case 'Monthly':
        return this.generateMonthlyReport(data);
      case 'Weekly':
        return this.generateWeeklyReport(data);
      case 'Incident':
        return this.generateIncidentReport(data);
      case 'Custom':
        return this.generateCustomReport(data);
      default:
        return this.generateSecurityReport(data);
    }
  }
}

// Utility function to download PDF
export function downloadPDF(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

// Utility function to generate HTML report
export function generateHTMLReport(data: ReportData): string {
  return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>${data.title}</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 0;
                padding: 20px;
                background-color: #f5f5f5;
            }
            .container {
                max-width: 800px;
                margin: 0 auto;
                background: white;
                padding: 30px;
                border-radius: 8px;
                box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            }
            .header {
                text-align: center;
                border-bottom: 2px solid #0ea5e9;
                padding-bottom: 20px;
                margin-bottom: 30px;
            }
            .header h1 {
                color: #0ea5e9;
                margin: 0;
                font-size: 28px;
            }
            .header p {
                color: #666;
                margin: 5px 0 0 0;
            }
            .stats {
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
                gap: 20px;
                margin: 30px 0;
            }
            .stat-card {
                text-align: center;
                padding: 20px;
                background: #f8fafc;
                border-radius: 8px;
                border-left: 4px solid #0ea5e9;
            }
            .stat-number {
                font-size: 32px;
                font-weight: bold;
                color: #0ea5e9;
                margin: 0;
            }
            .stat-label {
                color: #666;
                margin: 5px 0 0 0;
                font-size: 14px;
            }
            .content {
                margin: 30px 0;
                line-height: 1.6;
            }
            .footer {
                text-align: center;
                margin-top: 40px;
                padding-top: 20px;
                border-top: 1px solid #e5e7eb;
                color: #666;
                font-size: 12px;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>${data.title}</h1>
                <p>Generated on ${data.date}</p>
                <p>Report Type: ${data.type}</p>
            </div>
            
            <div class="stats">
                <div class="stat-card">
                    <div class="stat-number">${data.cameras}</div>
                    <div class="stat-label">Active Cameras</div>
                </div>
                <div class="stat-card">
                    <div class="stat-number">${data.alerts}</div>
                    <div class="stat-label">Total Alerts</div>
                </div>
                <div class="stat-card">
                    <div class="stat-number">${data.incidents}</div>
                    <div class="stat-label">Security Incidents</div>
                </div>
            </div>
            
            <div class="content">
                <h2>Report Details</h2>
                <p>${data.content}</p>
            </div>
            
            <div class="footer">
                <p>Generated by Aegis Spectra Security System</p>
                <p>© 2024 Aegis Spectra. All rights reserved.</p>
            </div>
        </div>
    </body>
    </html>
  `;
}